name: production deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  health-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.health-check.outputs.status }}
    steps:
      - name: Health check
        id: health-check
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://data.bodik.jp"
          expected-statuses: "200"


  deploy:
    runs-on: ubuntu-latest
    needs: [health-check]
    if: needs.health-check.outputs.status == 200
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      
      - name: GET CSV files
        run: |
          curl -sSL -o "./csv/440001oitacovid19patients.csv" $PATIENTS_DATA_URL
          curl -sSL -o "./csv/440001oitacovid19datasummary.csv" $DATA_SUMMARY_URL
          curl -sSL -o "./csv/440001oitacovid19finnumber.csv" $FINANCIAL_NUMBER_URL
          curl -sSL -o "./csv/440001oitacovid19finamount.csv" $FINANCIAL_AMOUNT_URL
          curl -sSL -o "./csv/440001oitacovid19fintype.csv" $FINANCIAL_TYPE_URL
          curl -sSL -o "./csv/440001oitaemploymentsubsidy.csv" $EMPLOYMENT_SUBSIDY_URL
        env:
          PATIENTS_DATA_URL: http://data.bodik.jp/dataset/f632f467-716c-46aa-8838-0d535f98b291/resource/3714d264-70f3-4518-a57a-8391e0851d7d/download/440001oitacovid19patients.csv
          DATA_SUMMARY_URL: http://data.bodik.jp/dataset/f632f467-716c-46aa-8838-0d535f98b291/resource/96440e66-3061-43d6-adf3-ef1f24211d3a/download/440001oitacovid19datasummary.csv
          FINANCIAL_NUMBER_URL: http://data.bodik.jp/dataset/a099a7d0-8393-4982-89c3-bee49ddfcecd/resource/a56764ef-baba-4972-8877-e773c24d27ca/download/440001oitacovid19finnumber.csv
          FINANCIAL_AMOUNT_URL: http://data.bodik.jp/dataset/a099a7d0-8393-4982-89c3-bee49ddfcecd/resource/9c609301-4800-4f06-a400-62ba5eb489ba/download/440001oitacovid19finamount.csv
          FINANCIAL_TYPE_URL: http://data.bodik.jp/dataset/a099a7d0-8393-4982-89c3-bee49ddfcecd/resource/3be72fdc-d8e7-4042-bbcd-e05e8dc6bae2/download/440001oitacovid19fintype.csv
          EMPLOYMENT_SUBSIDY_URL: http://data.bodik.jp/dataset/a099a7d0-8393-4982-89c3-bee49ddfcecd/resource/226c523f-178d-4180-8a1c-16e492757378/download/440001oitaemploymentsubsidy.csv

      - name: Generate data.json and news.json
        run: |
          pip install -r requirements.txt
          python tool/convert/main.py
        env:
          TZ: "Asia/Tokyo"

      - name: Slack Alert(generate json files)
        run: |
          curl -X POST \
          -H 'Content-type: application/json' \
          --data '{"text": "pushに失敗しました :cry: "}' ${WEBHOOK}
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        if: failure()
        
      - name: check diffs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./csv/*.csv && git diff --cached --exit-code || echo "::set-output name=diff::1"
          git add ./json/news.json && git diff --cached --exit-code || echo "::set-output name=diff::1"
        id: check_diffs
        
      - name: commit data.json and news.json
        run: |
          git commit -am "[ci skip] Update Data (commited by GitHub Actions)"
        if: steps.check_diffs.outputs.diff == 1

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
        if: steps.check_diffs.outputs.diff == 1

      
