name: development deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Generate data.json
        run: python tool/convert/convert_csv_to_json.py
        env:
          TZ: 'Asia/Tokyo'

      - name: commit data.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "[ci skip] Update Data (commited by GitHub Actions)"

      - name: Push data
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
