name: reviewdog

on:
  pull_request:
    branches:
      - master
jobs:
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.github_token }}
          level: warning
          locale: "US"
