name: update CSV data

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: GET CSV files
        run: |
          curl -sS -o "./csv/440001oitacovid19patients.csv" $PATIENTS_DATA_URL
          curl -sS -o "./csv/440001oitacovid19datasummary.csv" $DATA_SUMMARY_URL
        env:
          PATIENTS_DATA_URL: https://data-covid19-oita.netlify.com/csv/440001oitacovid19patients.csv
          DATA_SUMMARY_URL: https://data-covid19-oita.netlify.com/csv/440001oitacovid19datasummary.csv

      - name: check diffs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./csv/*.csv && git diff --cached --exit-code || echo "::set-output name=diff::1"
        id: check_diffs

      - name: Generate data.json
        run: python tool/convert/data_handler.py
        env:
          TZ: "Asia/Tokyo"
        if: steps.check_diffs.outputs.diff == 1

      - name: commit data.json
        run: |
          git commit -am "[ci skip] Update Data (commited by GitHub Actions)"
        if: steps.check_diffs.outputs.diff == 1

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
        if: steps.check_diffs.outputs.diff == 1
