name: update data csv

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: GET data csv file
        run: |
          curl -sS -o "./csv/440001oitacovid19patients.csv" $PATIENTS_DATA_URL
          curl -sS -o "./csv/440001oitacovid19datasummary.csv" $DATA_SUMMARY_URL
        env:
          PATIENTS_DATA_URL: https://data-covid19-oita.netlify.com/csv/440001oitacovid19patients.csv
          DATA_SUMMARY_URL: https://data-covid19-oita.netlify.com/csv/440001oitacovid19datasummary.csv

      - name: Generate data.json
        run: python tool/convert/data_handler.py
        env:
          TZ: "Asia/Tokyo"

      - name: commit data.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "[ci skip] Update Data (commited by GitHub Actions)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
